/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_parsemis_miner_environment_LocalEnvironment */

#ifndef _Included_de_parsemis_miner_environment_LocalEnvironment
#define _Included_de_parsemis_miner_environment_LocalEnvironment
#ifdef __cplusplus
extern "C" {
#endif
#undef de_parsemis_miner_environment_LocalEnvironment_serialVersionUID
#define de_parsemis_miner_environment_LocalEnvironment_serialVersionUID 1LL
/*
 * Class:     de_parsemis_miner_environment_LocalEnvironment
 * Method:    getClockTicks
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_parsemis_miner_environment_LocalEnvironment_getClockTicks
  (JNIEnv *, jclass);

/*
 * Class:     de_parsemis_miner_environment_LocalEnvironment
 * Method:    getCPUtime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_parsemis_miner_environment_LocalEnvironment_getCPUtime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
